import Head from "next/head";
import Image from "next/image";

import NavBar from "@/components/NavBar";
import HeroSection from "../components/HeroSection";
import NewsSection from "@/components/NewsSection";
import ProductSection from "@/components/ProductSection";
import InfoNavSection from "@/components/InfoNavSection";
import LastSection from "@/components/LastSection";

import { newsData, productsData } from "@/data/indexPage";

import iconImg from "../public/icons/companyIcon.png";
import { MdVerticalAlignTop } from "react-icons/md";
import { useEffect, useState } from "react";

export default function Home() {


  return (
    <>
      <Head>
        <title>Warner Global Tech</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <main className="" style={[]}>
        <NavBar />
        <HeroSection />
        <NewsSection data={newsData} />
        <ProductSection data={productsData} />
        <InfoNavSection />
        <LastSection />
      </main>
    </>
  );
}
